### ISSUE TITLE
Don't require tests to run to commit

### ISSUE THREAD

**Issue by OmgImAlexis** [mqttjs/MQTT.js#1098]
So about 20 tests failed when I tried committing to the last two PRs I opened. Since you now have Github actions auto running your tests I feel like it'd make sense to remove the need for devs to run the tests and instead allow them to rely on the ci to do them. This also prevents the whole "but it's working for me" issue.

PING: @mcollina

**Comment by mcollina** [comment]
This further decreases the impact of the flaky test suite we have. Effort should be spent in making the tests more robust, not in skipping them :(.

**Comment by YoDaMa** [comment]
I'm not seeing the failed test runs, could you clarify? tests failed locally?

**Comment by OmgImAlexis** [comment]
The tests fail for me as I have a really slow Mac and I was running a load of background tests.

The idea for only using ci is it avoids flaky ness by controlling as much of the environment as possible. This was it should just be the code itself and not a dependency or environment issue.

**Comment by YoDaMa** [comment]
So I’m a bit confused still. Is there a requirement for having tests run locally in order to commit? 

The tests are definitely flakey, for sure, and need to be cleaned up more than they already have been. But in the CI (Github Actions) they’re doing much better than before. what do you mean by “Don’t require tests to run to commit”? As in, don’t require them to run locally?

**Comment by OmgImAlexis** [comment]
Yes, we should be able to commit just as you can using Github website. I had to run `--no-verify` just to get past the flakey tests.

The main thing we need is the CI to pass not the random devs that're putting in PRs. I get it's be good if it also passed locally but that shouldn't be a requirement.
