### ISSUE TITLE
Request-response without MQTT 5

### ISSUE THREAD

**Issue by Florimond** [mqttjs/MQTT.js#1118]
I need to implement a request-response pattern without using the tools provided by MQTT 5.

It seems fairly straightforward but is it? Is the following solution valid?

- I publish a message with QoS > 0.
- I immediately store a callback in a JavaScript object, let's call it `cbStore`, using `getLastMessageId()` for the key.
- When I receive a message I retrieve the message id from the packet payload.
- I get the corresponding callback from the `cbStore` and delete the key, then execute the callback with the packet as a parameter.

It feels like I'm missing something...

**Comment by jdiamond** [comment]
No, the ID in puback, pubrec, etc, packets is used to tell the sender to release the message so they never send it again. A response in MQTT 5 terms is very different and would be a new message with an unrelated ID. MQTT 5 uses a new property called "Correlation Data" to match the response to the original request. You could definitely do the same thing without MQTT 5, but you'd have to put the correlation data in your message payload (both the request and response) or maybe you could put it in the topics.

**Comment by Florimond** [comment]
Thanks for your answer.
The ID is sent to the server, and this particular server ([Emitter](https://github.com/emitter-io)) sends the id back with the response. So, I already have that correlation data.
And what would be the purpose of this `getLastMessageId()` if it wasn't to do that kind of matching?

**Comment by jdiamond** [comment]
Packet IDs are only sent back to clients in acknowledgement packets. There is no data in those acks except for the packet ID. If all you care about is knowing when the packet is acknowledged, pass a callback into the publish method.

MQTT 5 describes a way for clients to respond to requests from other clients. The packet IDs aren't useful for that (the response will almost definitely have a different packet ID than the request) which is why they added the correlation data property.

I've never had a reason to know the packet ID assigned to a message and can't see why it would be useful outside the client.

**Comment by Florimond** [comment]
> Packet IDs are only sent back to clients in acknowledgement packets.

Not with Emitter.io, that's what I mean. If QoS is > 0, you actually have the packet ID of the original request sent back with the actual response to this request. Those are requests, like `me` or `keygen`, made to the server itself, not destined to other clients.

In that case, I suppose my approach is valid...

**Comment by jdiamond** [comment]
Yeah, if that custom behavior exists in your broker and you want to rely on it, I think what you described is how I would do it, too.
