### ISSUE TITLE
What event is fired when network connection is lost?

### ISSUE THREAD

**Issue by chainhead** [mqttjs/MQTT.js#1122]
# Case 1

Switch of WiFi on laptop and try to connect to `mqtt://test.mosquitto.org:1883`. `error` event with `ENOTFOUND` is raised. This is good.

# Case 2

Switch on WiFi on laptop, connect to `mqtt://test.mosquitto.org:1883` and subscribe to a topic string. Messages are received successfully. Now, switch off WiFi on laptop; no events are raised. Turn back on WiFi; messages are received successfully.

What is the expected event when a client loses connection while subscribing?

**Comment by jdiamond** [comment]
You should see an offline event but you will have to wait for the keep alive timer to expire if you're not actively publishing messages. That is when it will try to send a pingreq packet, fail, and then emit the offline event. It will then emit a reconnect event every time it tries to reconnect.

**Comment by chainhead** [comment]
I will be _actively_ publishing. In fact, I want to pause that publish and inform upstream when a disconnect happens.

Are you saying that, in case of disconnect, until the next `PINGREQ` fail, I won't get an event to handle? And, when I do get that event, it will be a reconnect event?

**Comment by jdiamond** [comment]
When the client tries to write to the socket, it should fail which the client will interpret as now being offline. If you are publishing, that should happen when you try to publish. If you are not publishing or otherwise writing packets, you will have to wait until it tries to write a pingreq packet. In either case, the client should emit an offline event. The client will then try to reconnect and emit a reconnect event. When it finally connects, it will emit a connect event.

**Comment by Global-Ekons** [comment]
Error 104

The system32 folder is mia, now it doesn't matter what I try, won't even
reinstall win10, as it doesn't pass Boot.

Boot option doesn't work either, or any other command doesn't work either.


LAPTOP, DELL LATITUDE E6540, 64bit with 16gb ram.
Win10 System was never reinstalled after 2016, as updates did enough, was
though a Win8.1 beforehand.
