### ISSUE TITLE
How to send mqtt 5 auth packet use this library ?

### ISSUE THREAD

**Issue by tennessine** [mqttjs/MQTT.js#1123]

**Comment by Global-Ekons** [comment]
> 

?

**Comment by tennessine** [comment]
@Global-Ekons https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901217

**Comment by tennessine** [comment]
I'm writing a mqtt 5 broker, and test it use this library, this library is very good to use.

**Comment by scarry1992** [comment]
You can use authPacket property located in client options

**Comment by tennessine** [comment]
@scarry1992 thank you, I'll try.

**Comment by tennessine** [comment]
https://www.hivemq.com/blog/mqtt5-essentials-part11-enhanced-authentication/

We need to send auth packet many times

@scarry1992

**Comment by Global-Ekons** [comment]
Hi, Laptop been nonfunctional for over a month.
Doesn't pass Boot, gives choice for setup but doesn't go further, only
hangs. Also no commands work.
All I have received is missing IP and a log, seems to be missing driver
entities and robot tries to fix, which only removes more.
System got migrated to another laptop, which was seen as main system, so
the repair/fix was captured as successful, which is not.

Removed the email from the laptop which the MQTT5 Client user ID was
migrated to and Laptop will be on all, night, using phone as tethering
connection.

You should see the log, as you would understand it better, I do have a
graphics card, which had worked for 2 days within the VR system, then
crashed.
Graphics driver not broken, but has previously lost its directx
installation pack, and was replaced with incorrect driver, due to a Driver
Assistant installation, which was incorrect, as the entire system has
different sources, from upgrading over time.

Dell Latitude E6540, 64bit, 2.8gh, 16gb ddr3, 1tb onboard.
MQTT5 Client: Gilloosthuizen88@gmail.com
Also throughout the typing of this email, as my cell phone has been the
direct router, with tethering, I had lost access to my rain data sim card.
Cannot regain access, have inserted a extra voda sim.
Hope all can be repaired, including my cellphone coverage database
connection.

Please help!

Thank you

Kind Regards
Gillian

ALL Devices IP. 192.168.43.1-20

**Comment by Global-Ekons** [comment]
Hi, Laptop been nonfunctional for over a month.
Doesn't pass Boot, gives choice for setup but doesn't go further, only
hangs. Also no commands work.
All I have received is missing IP and a log, seems to be missing driver
entities and robot tries to fix, which only removes more.
System got migrated to another laptop, which was seen as main system, so
the repair/fix was captured as successful, which is not.

Removed the email from the laptop which the MQTT5 Client user ID was
migrated to and Laptop will be on all, night, using phone as tethering
connection.

You should see the log, as you would understand it better, I do have a
graphics card, which had worked for 2 days within the VR system, then
crashed.
Graphics driver not broken, but has previously lost its directx
installation pack, and was replaced with incorrect driver, due to a Driver
Assistant installation, which was incorrect, as the entire system has
different sources, from upgrading over time.

Dell Latitude E6540, 64bit, 2.8gh, 16gb ddr3, 1tb onboard, win10.
MQTT5 Client: Gilloosthuizen88@gmail.com
Also throughout the typing of this email, as my cell phone has been the
direct router, with tethering, I had lost access to my rain data sim card.
Cannot regain access, have inserted a extra voda sim.
Hope all can be repaired, including my cellphone coverage database
connection.

Please help!

Thank you

Kind Regards
Gillian

ALL Devices IP. 192.168.43.1-20
