### ISSUE TITLE
Connection closed before receiving a handshake response

### ISSUE THREAD

**Issue by guestisp** [mqttjs/MQTT.js#1126]
I'm getting the following error:
`WebSocket connection to 'wss://my.mosquitto.server:8083/' failed: Connection closed before receiving a handshake response`

I think it's only happening with Chrome, firefox doesn't trigger any error. Even connecting from command line (`websocat`) works fine.

Any idea on what happened ? I've not changed anything regarding websockets in the application (vue). A know bug caused by a chrome update ?

**Comment by guestisp** [comment]
It's cookie related. A fix is to set `websockets_headers_size 4096` in mosquitto.conf

Isn't possible to skip sending cookies when using websockets ? Because based on the cookie size, the server should be reconfigured.

**Comment by Global-Ekons** [comment]
Hi, Laptop been nonfunctional for over a month.
Doesn't pass Boot, gives choice for setup but doesn't go further, only
hangs. Also no commands work.
All I have received is missing IP and a log, seems to be missing driver
entities and robot tries to fix, which only removes more.
System got migrated to another laptop, which was seen as main system, so
the repair/fix was captured as successful, which is not.

Removed the email from the laptop which the MQTT5 Client user ID was
migrated to and Laptop will be on all, night, using phone as tethering
connection.

You should see the log, as you would understand it better, I do have a
graphics card, which had worked for 2 days within the VR system, then
crashed.
Graphics driver not broken, but has previously lost its directx
installation pack, and was replaced with incorrect driver, due to a Driver
Assistant installation, which was incorrect, as the entire system has
different sources, from upgrading over time.

Dell Latitude E6540, 64bit, 2.8gh, 16gb ddr3, 1tb onboard.
MQTT5 Client: Gilloosthuizen88@gmail.com
Also throughout the typing of this email, as my cell phone has been the
direct router, with tethering, I had lost access to my rain data sim card.
Cannot regain access, have inserted a extra voda sim.
Hope all can be repaired, including my cellphone coverage database
connection.

Please help!

Thank you

Kind Regards
Gillian

ALL Devices IP. 192.168.43.1-20
