### ISSUE TITLE
Unexpected behavior with client option "clean" = true while offline

### ISSUE THREAD

**Issue by Poutsh** [mqttjs/MQTT.js#1129]
Hi, I'm currently facing a behavior with the mqtt client option **clean**.
Your documentation specifically states :

> clean: true, set to false to receive QoS 1 and 2 messages while offline

So if I understand well, when **clean = true**, I should not receive QoS 1 and 2 messages while offline. I tested it with a very simple broker and publisher/subscriber with two PC communicating with each other. When I disconnect from the internet the one that publishes the messages, wait for one minute, and then reconnects it, all the QoS 1 messages are then well published and received by the subscriber which is not what your documentation is saying.

So with **clean = true, I receive all QoS 1 messages sent while offline** which is unexpected.

Here is my code to reproduce this behavior :

Server code :
```javascript
//broker.js
var mosca = require('mosca');
var settings = {
                port:1883
                }

var server = new mosca.Server(settings);

server.on('ready', function(){
console.log("ready");
});
```

Publisher code :
```javascript
//publisher.js
var mqtt = require('mqtt');
var it = 0;
var mqttClienOpts = {
        clean: true,
        queueQoSZero: false,
}

var client  = mqtt.connect('mqtt://ip_of_my_pc', mqttClienOpts);

client.on('connect', function () {
        setInterval(function() {
                client.publish('myTopic', 'Hello mqtt '+it, {qos: 1, retain: false});
                console.log('Message Sent '+ it);
                it = it + 1;
        }, 2000);
});

client.on('error', function() {
        console.log('error');
});

client.on('offline', function() {
        console.log('offline');
});
```

Subscriber code :
```javascript
//subscriber.js
var mqtt = require('mqtt');
var client  = mqtt.connect('mqtt://ip_of_my_pc);
client.on('connect', function () {
    client.subscribe('myTopic')
});
client.on('message', function (topic, message) {
    context = message.toString();
    console.log(context)
});
```

And here is my  **package.json** to know which versions I'm using :
```json
{
  "name": "mqtt_server",
  "version": "1.0.0",
  "description": "Simple mqtt",
  "main": "broker.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node broker.js"
  },
  "author": "me",
  "license": "ISC",
  "dependencies": {
    "node-gyp": "^7.0.0",
    "node-pre-gyp": "^0.14.0",
    "node-pty": "^0.9.0",
    "moment": "^2.20.0",
    "mosca": "^2.8.3",
    "mqtt": "^3.0.0"
  }
}
```

**Comment by jdiamond** [comment]
Your publisher is queueing publishes while it's offline. Once it reconnects, it will flush them all. Your example code has a `mqttClienOpts` to disable this, but is not actually passing it in to `connect`.

Besides that, the clean flag is for the subscriber to use, not the publisher.

**Comment by Poutsh** [comment]
> Your example code has a `mqttClienOpts` to disable this

I'm sorry I forgot to add it when I wrote my sample code on the issue, but the issue is still happening when I'm correcting it, it flushes all the QoS 1 messages no matter what.

```javascript
var mqtt = require('mqtt');
var it = 0;
var mqttClienOpts = {
        clean: true,
        queueQoSZero: false,
}

var client  = mqtt.connect('mqtt://192.168.1.99', options=mqttClienOpts);

client.on('connect', function () {
        setInterval(function() {
                client.publish('myTopic', 'Hello mqtt '+it, {qos: 1, retain: false});
                console.log('Message Sent '+ it);
                it = it + 1;
        }, 2000);
});

client.on('error', function() {
        console.log('error');
});

client.on('offline', function() {
        console.log('offline');
});
```

> Besides that, the clean flag is for the subscriber to use, not the publisher.

So, if I understand well, it is impossible to disable queuing QoS 1 messages in the publisher but it's possible for the subscrber?
I'm using the same options for the subscriber now and I'm still receiving all the messages when I cut the internet connection publisher or subscriber side.

```javascript
var mqtt = require('mqtt')
var mqttClienOpts = {
        clean: true,
        queueQoSZero: false,
}
var client  = mqtt.connect('mqtt://192.168.1.99', options=mqttClienOpts)
client.on('connect', function () {
    client.subscribe('myTopic')
});
client.on('message', function (topic, message) {
context = message.toString();
console.log(context)
});
```

Also, my "offline" debug message seems to be printed only when I re-enable my internet connection (by replugging the internet cable), and when it happens, that's when every messages get flushed.

So I don't quite understand why I'm still receiving those messages, are QoS1 messages simply not affected by the "clean" flag?

**Comment by jdiamond** [comment]
Yes, QoS 1 messages are always stored so they can be sent after reconnecting and there is no option to disable that because that is the primary purpose of publishing with QoS 1. If you didn't care if the messages were ever received, you would just publish with QoS 0.

On the subscriber side, setting clean to true is a way of telling the broker to discard any messages received for that client while it was offline. If the broker isn't doing that, there's nothing MQTT.js can do to change that broken behavior. But you're also not subscribing with QoS 1 so no messages on that topic should be saved for your client while it's offline anyways. Maybe it's a timing issue?

- subscriber reconnects
- publisher reconnects and flushes all qos 1 messages
- subscriber receives them because it's currently connected

It looks like you're using Mosca, which is abandoned AFAIK. Aedes is its replacement, but I think most people do testing with mosquitto. I don't know if Mosca is broken in this regard, but it might be nice to test with another broker to see if you get the same behavior.

When I've done testing before by just disabling the WiFi on my laptop, I saw that the offline event was not emitted immediately. It seemed like MQTT.js was not able to detect that the connection was broken until it tried to use it by sending a keep alive packet some seconds later. MQTT.js relies on Node.js to emit an error when the connection is broken and Node.js probably relies on the OS. I think in a normal scenario, a TCP reset packet would get sent and everybody would notice right away, but that doesn't seem to happen by just disabling the network.
