### ISSUE TITLE
Connection problem with IPv6 addresses

### ISSUE THREAD

**Issue by flipback** [mqttjs/MQTT.js#1130]
Hello,
we are trying to use  MQTT.js with IPv6 addresses but we can't connect an MQTT broker:

```js
client = mqtt.connect('ws://[::1]:9001');
```

This code throws an exception:

```
 'WebSocket': The URL 'ws://::1:9001/' is invalid.
```

It seems the library skips `[]`. I've checked this URL with another library. It works fine.

**Comment by seriousme** [comment]
Hi,

I did some digging and the problem seems to be in Nodejs url.parse used in [lib/connect/index.js](https://github.com/mqttjs/MQTT.js/blob/eedc2b26cd6063a0b1152432a00f70de5e0b9bae/lib/connect/index.js#L63)

```javascript
url.parse('ws://[::1]:9001/',true)
Url {
  protocol: 'ws:',
  slashes: true,
  auth: null,
  host: '[::1]:9001',
  port: '9001',
  hostname: '::1',
  hash: null,
  search: null,
  query: [Object: null prototype] {},
  pathname: '/',
  path: '/',
  href: 'ws://[::1]:9001/'
}
```
as you can see the brackets are in the host but not in the hostname anymore.

Whereas the URL constructor works fine:
```javascript
new URL('ws://[::1]:9001/')
URL {
  href: 'ws://[::1]:9001/',
  origin: 'ws://[::1]:9001',
  protocol: 'ws:',
  username: '',
  password: '',
  host: '[::1]:9001',
  hostname: '[::1]',
  port: '9001',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

[Node's documentation](https://nodejs.org/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost) is quite clear on the subject:
```quote
Use of the legacy url.parse() method is discouraged. Users should use the WHATWG URL API. Because the url.parse() method 
uses a lenient, non-standard algorithm for parsing URL strings, security issues can be introduced. Specifically, issues with host 
name spoofing and incorrect handling of usernames and passwords have been identified.
```

An obvious fix seems to be to replace `var parsed = url.parse(brokerUrl, true)` by `var parsed = new URL(brokerUrl)` but I haven't tested it. There are [a few more places](https://github.com/mqttjs/MQTT.js/search?q=url.parse&unscoped_q=url.parse) where url.parse is used. So whoever is going to fix this might want to fix them too.

Kind regards,
Hans

**Comment by seriousme** [comment]
It turned out to be a bit more work as the URL class is a bit special.

I got a version working (although CI fails on node 10 due to a unrelated problem) at https://github.com/seriousme/MQTT.js/tree/replace-url-parse-by-url-class

I can do a PR if you like.

Kind regards,
Hans
