### ISSUE TITLE
Version 4.2.0: ws does not work in the browser

### ISSUE THREAD

**Issue by ttsirkia** [mqttjs/MQTT.js#1141]
After the latest update, my web page using mqtt and MapBox GL JS library fails to fetch resources and gives this error:

`Error: ws does not work in the browser. Browser clients must use the native WebSocket object`

The error comes from inside mapbox-gl-js library. Does the new version somehow make global changes to some prototypes etc. which would cause this? The error disappeared after downgrading back to 4.1.0.

**Comment by ttsirkia** [comment]
Both libraries are attached with `script` tags to the page.

**Comment by YoDaMa** [comment]
The 4.2.0 does change the internal use of ws to use its internal implementation of streams for web sockets. Can you provide a way to reproduce this issue so it can be investigated and fixed?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ttsirkia** [comment]
@YoDaMa I'll try to provide a simple example. The problem is with the MapBox authentication token to make it worl.

**Comment by ttsirkia** [comment]
OK, mapbox-gl-js is not related here. It seems that the unpkg version causes this.

```
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <script src="https://unpkg.com/mqtt/dist/mqtt.min.js"></script>
    <script>
      var client = mqtt.connect('wss://mqtt.hsl.fi:443');
      client.on('connect', function() {});
    </script>
  </head>
  <body>



  </body>
</html>
```

This will cause the error.

**Comment by lucaong** [comment]
Observing the same issue in a browser app built with Webpack. Since the 4.2.0 update, the app breaks with:

  `Error: ws does not work in the browser. Browser clients must use the native WebSocket object`

Downgrading to `4.1.0` fixes it. Is `ws` used also for when using `MQTT` in a browser environment?

**Comment by lucaong** [comment]
@YoDaMa It looks like `MQTT` now uses `ws` instead of `websocket-stream`: https://github.com/mqttjs/MQTT.js/blob/b2c121511c7437b64724e9f1e89ebcd27e3c2cce/lib/connect/ws.js#L3

The problem is that [`ws` only works in Node](https://github.com/websockets/ws#ws-a-nodejs-websocket-library), not in the browser, [differently from `websocket-stream`](https://github.com/maxogden/websocket-stream#usage). Therefore, `4.2.0` breaks browser builds.

One way to fix this would be to replace `ws` with the native `WebSocket` in browser builds, like [`websocket-stream` does](https://github.com/maxogden/websocket-stream/blob/3f39dcbc098f661ee12d7deba297b1420a0a0e07/package.json#L43).

**Comment by YoDaMa** [comment]
So unfortunately the testing infrastructure we have didn’t test for browser functionality like I thought it would during the release process.

The changes made were to remove websocket-stream as a dependency, which in turn uses ws as a dependency, and instead simply use ws for performance and reliability improvements. This change seems to have broken webpack though.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by YoDaMa** [comment]
yeah so like you said we need to implement an isomorphism for the browser compatibility to work with the Websocket in browser builds. I'm working on a PR rn to fix this.

**Comment by seriousme** [comment]
FYI: 
Looking at the [docs for `ws`](https://www.npmjs.com/package/ws) the isomorphic fix seems to be easy:

```quote
Note: This module does not work in the browser. The client in the docs is a reference to a back end with the role of a
client in the WebSocket communication. Browser clients must use the native WebSocket object. To make the same 
code work seamlessly on Node.js and the browser, you can use one of the many wrappers available on npm, 
like isomorphic-ws.
```

and `isomorphic-ws` usage seems to be simple as well: https://www.npmjs.com/package/isomorphic-ws

**Comment by ysfscream** [comment]
Yes, the `ws` module does not work in the browse.

![image](https://user-images.githubusercontent.com/21299158/90464753-91e3bf80-e140-11ea-8fce-5acc24b5389b.png)

**Comment by YoDaMa** [comment]
Yes there’s a draft PR fixing this.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pr0x1** [comment]
Hi @YoDaMa 
Thanks for you answer to solve this issue.

when the update to solve the bug will be release?

Reggards.

**Comment by YoDaMa** [comment]
Can someone in this thread try using the patch provided in https://github.com/mqttjs/MQTT.js/pull/1145 . I've tested it manually on my machine and it seems to be working but I'd like other folks trying it out. @pr0x1 @ysfscream @lucaong

**Comment by lucaong** [comment]
Thanks, I’ll try it tomorrow and let you know.

**Comment by pr0x1** [comment]
Hi @YoDaMa  I was testing but the issue continues.

![mqtt js](https://user-images.githubusercontent.com/26003158/90703359-2c342800-e253-11ea-95f5-865c1fdcf2ba.JPG)
 
i'm using the following script
<script** src="https://unpkg.com/mqtt/dist/mqtt.min.js"></script>

Reggards.

**Comment by YoDaMa** [comment]
Hey sorry to clarify you’ll need to manually pull the branch to a folder, run “npm run browser-build” then replace the src line in your code with the full path to the “dist/mqtt.min.js” that was generated

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ysfscream** [comment]
@YoDaMa 👍 Thanks for the fix. I will test it later.

**Comment by nosovk** [comment]
really say there is lots of problems with running mqtt in browser. Not only ws, but `readable-stream` fails to run in browser if node shims are not provided.
https://github.com/nodejs/readable-stream/issues/412 that lead to goal of supporting shim free version in next release https://github.com/nodejs/readable-stream/issues/439 (because webpack 5 will drop node shim support https://webpack.js.org/migrate/5/#test-webpack-5-compatibility

even if we removed methods that require shiming from mqtt (https://github.com/mqttjs/MQTT.js/pull/1134) we still can't use mqtt.js in browser without hacks because of underlying libs. As a result we need to maintain hacks like that https://github.com/sclausen/ngx-mqtt/pull/158/files

really say I don't see how to improve situation, except providing node shims via webpack in each dependant project. Problem with WS is just one of the symptoms.

**Comment by lucaong** [comment]
@YoDaMa , I just tried out your patch in #1145 and it works: no error, and MQTT connects successfully while running in the browser. 👍

**Comment by lucaong** [comment]
@nosovk I am not sure what you mean, I have been using MQTT.js in the browser for years now, connecting via Websocket, and never experienced any problem. Maybe I miss some context, but I really think that supporting browsers is a very important goal for MQTT.js, as that's one of the primary environments where JS runs.

**Comment by YoDaMa** [comment]
yes sorry @nosovk I'm a bit confused at what you're getting at

**Comment by YoDaMa** [comment]
release 4.2.1 (#1149) fixes this.

**Comment by lucaong** [comment]
Thanks @YoDaMa for fixing this :)

**Comment by nosovk** [comment]
@YoDaMa @lucaong sorry for late response, I'le provide some explanation.

Current browser version of MQTT.js is build via browserify. Browserify is predecessor of webpack, it's a bundler. What does it mean? When you make browser build of mqtt.js you ship mqtt bundle combined with all deps. For example that one https://github.com/mqttjs/MQTT.js/blob/master/package.json#L76 and other.

It's ok, if you add mqtt js like external module in yours application. That bundle is minified and has no external requirements. 

But some time after Browserify there was Webpack/Rollup was invented. They works in a  bit different.way. For webpack good library is not the one which provides compiled\minified js file. For webpack\rollup good dependency is js code, which is not minified and surely not bundled with deps. Rollup will try to treeshacke librarry deps with other packages deps, and split to smaller and probably even lazy loaded chunks. And splitting/minifying should be done according to the project config (not library config).

Good example is Angular. Angular requires libraries to provide es, umd, esm etc bundles. Package spec: https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview

Alternate solution - allow Angular to build all needed versions itself. But it's only possible only if source code of the library is ready to be complied by webpack. In case of mqtt it means that nodejs specific methods shouldn't be invoked. For example process etc. Currently mqtt code could be builded with webpack\rollup, but one of dependant libs - is not.

webpack\rollup couldn't process nodejs/readable-stream. 
https://github.com/nodejs/readable-stream/issues/426
https://github.com/nodejs/readable-stream/issues/412

It will be fixed, but currently all libs that depend on readable-stream have to use browserified (non tree shakable) version or enable node shims (polyfils). For webpack versions prior to 5 it wasn't a big problem because of default webpack configuration have those polyfils enabled. But for Rollup or Angular projects polyfills should be explicitly defined. For example check https://github.com/sclausen/ngx-mqtt/commit/b488b801befd047c139da7ea878526382b0dcdd0
It's surely not a good solution
.
Probably after https://github.com/nodejs/readable-stream/issues/439 issues with node intrnals used in browser will disappear, and then we will be able to use mqtt.js in Angular project without hacks.
 
Using mqtt with webpack now could be a bit tricky (with webpack 5 probably not possible)
