### ISSUE TITLE
Behavior of "resubscribe" option on manual "reconnect()" 

### ISSUE THREAD

**Issue by AWoelfel** [mqttjs/MQTT.js#1216]
Hi, 
i stumbeled over a unexptected behavior.
Can you please clearify whether this is exptecter or not. Thanx in advance.

I user mqtt to establish a TLS WS connection to a mosquitto broker.
I do an manual reconnect and expected all the subscriptions are carried over into the new connection.

A minimal viable example can be found here : https://jsfiddle.net/3c8jzv96/7/
After the reconnect no more messages are received.

Alex

AB#8867200

**Comment by sectokia** [comment]
I went to track this down, and maybe find a way to call _resubscribe to get around this bug and have it resubscribe your topics...

But the problem is much much deeper.

I would go so far as to say that 'reconnect()' is completely broken and should not be used at all. It causes the state of the client object to be extremely weird.... for example if you add to your code:

```
		client.on('connect',function()
		{
			appendLine('disconnecting? '+client.disconnecting);
		});
```

Then even after the reconnect the client still thinks its in disconnecting state, and basically lots of things break, including reconnection and even subscribing and recieving packets. At the moment there is no way around this other to call connect() , which means you have to setup the subscriptions again.

**Comment by AWoelfel** [comment]
Hi sectokia, 

thx for having a look!
Currently i do exaclty what you suggested. I track all my subscriptions and resubscribe after "reconnect" (ending the current connection and reestablish a fresh one)

**Comment by sectokia** [comment]
I recommend switching to the Eclipse Paho JavaScript Client for browser side client work.

mqtt.js for browser has way too many bugs, and for some absurd reason is an order of magnitude bigger and slower ( mqtt.is for browser is over 16,000 lines?! includes node.js stuff that only runs on server??)

**Comment by KUGDev** [comment]
Dug into the 'client.js' code, it turned out that the topic is not added to the reconnection object only by the resubscribe variable set to 'true'. It turns out that you also need to set the reconnectionPeriod > 0. In theory, if you properly adjust the reconnection mechanism, as another workaround, you can set the reconnection period to 2147483647, which corresponds to the maximum positive value of a 32-bit number.
![image](https://user-images.githubusercontent.com/29352750/144102804-9013122f-bac5-42a4-9f1d-642c39d159c8.png)
![image](https://user-images.githubusercontent.com/29352750/144102698-a3899f5f-cd18-4ec9-9b5e-b39c0e51a0c4.png)
