### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by roysG** [mqttjs/MQTT.js#1275]
You made awesome library and it works great!

I have a little problem that i have to solve in some way:

Today I have 3 servers for high availability connect to  same broker mqtt.
each server subscribe to same topic id.

My problem is, when i send message to topic, all the three severs get it.
I need to handle this by a way, that in case 1 server get the topic all the others servers will ignore it.

Does it possible to do in general with the mqtt and your library support it?

Thanks for your time!

**Comment by redboltz** [comment]
Let me clarify the situation.
Your 3 servers use MQTT.js as client and you use some broker (not MQTT.js). Is that right?

If the servers (brokers) you are using support Shared Subscriptions, it is possible.
Shared Subscriptions is MQTT v5 feature.
See https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901250

If the servers support Shared Subscriptions then `Shared Subscription Available` property should be contained CONNACK packet.
See https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901093
NOTE: Some of brokers might not return `Shared Subscription Available` even if they support Shared Subscriptions. So it is worth trying the following step even if `Shared Subscription Available` is not returned.

In order to use Shared Subscription functionality, your 3 servers subscribe `$share/your_sharename/topicfilter`.

For example,
3 servers subscribe `$share/sn1/topic1`, and then the publisher publish to some message to `topic1` then one of 3servers receives it and other 2 servers don't receive it. When the publisher publish again, the different server from the last time receives the message. The strategy of deliver is not defined by MQTT v5 spec. Just one of subscriber that has the same share_name. But broker usually use round robin strategy.

**Comment by roysG** [comment]
About your question, yes i am using mqtt in server called: "emqx" belongs of company: "emqx.io"

**Comment by redboltz** [comment]
It seems that https://www.emqx.io/mqtt/mqtt5 supports Shared Subscriptions.
So my comment approach should work.

**Comment by roysG** [comment]
Thanks i will check and update

**Comment by roysG** [comment]
Works!
