### ISSUE TITLE
Moquitto broker is active but I keep getting Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by disizme** [mqttjs/MQTT.js#1279]
The broker service is working fine in the server but cannot get mqtt client connect.
It was working fine until yesterday.

error Error: getaddrinfo ENOTFOUND mqtt.kipuwex.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'mqtt.kipuwex.com'
}

I had the same issue last week but it got solved on its own. There is no error in the server logs as well. 
Please help solve this recurring issue.

**Comment by kevingtzz** [comment]
I have the same issue.

Error: getaddrinfo ENOTFOUND 'test.mosquitto.org'
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: "'test.mosquitto.org'"
}

**Comment by UtmostCreator** [comment]
same issue

**Comment by UtmostCreator** [comment]
@kevingtzz, @disizme
I have managed to figure it out!

Take a look here:
```js
var mqtt = require("mqtt");
/* Possible connection brokerUrls:
 * ws://test.mosquitto.org:8080/mqtt
 * mqtt://test.mosquitto.org:8080/mqtt
 * ws://broker.hivemq.com:8000/mqtt
 */
var client = mqtt.connect("ws://test.mosquitto.org:8080/mqtt");

client.on("connect", function () {
  client.subscribe("presence", function (err) {
    if (!err) {
      client.publish("presence", "Hello mqtt");
    }
  });
});

client.on("message", function (topic, message) {
  // message is Buffer
  console.log(message.toString());
  client.end();
});
```

**Comment by YoDaMa** [comment]
Thanks for filing this issue. @OmgImAlexis did you work on the CLI tool previously? Could you provide a bugfix?

**Comment by miriki** [comment]
And I get this error since yesterday, right after updating ~7 adapters. I tried:
```
iob stop all
iob stop
sudo reboot
...
iob start
iob start admin
iob start mqtt
```
And I get in the log:
```
mqtt.0				2022-04-17 14:15:52.762	info	Adapter is disabled => stop

mqtt.0				2022-04-17 14:15:42.981	info	Disconnected from localhost
mqtt.0				2022-04-17 14:15:42.979	error	Client error:Error: getaddrinfo ENOTFOUND admin
mqtt.0				2022-04-17 14:15:42.967	info	Reconnected to localhost
mqtt.0				2022-04-17 14:15:32.960	info	Disconnected from localhost
mqtt.0				2022-04-17 14:15:32.958	error	Client error:Error: getaddrinfo ENOTFOUND admin
mqtt.0				2022-04-17 14:15:32.946	info	Reconnected to localhost
mqtt.0				2022-04-17 14:15:22.938	info	Disconnected from localhost
mqtt.0				2022-04-17 14:15:22.936	error	Client error:Error: getaddrinfo ENOTFOUND admin
mqtt.0				2022-04-17 14:15:22.917	info	Reconnected to localhost
mqtt.0				2022-04-17 14:15:12.903	error	Client error:Error: getaddrinfo ENOTFOUND admin

mqtt.0				2022-04-17 14:15:12.471	info	Try to connect to mqtt://Admin:*******************@localhost:1883?clientId=iobroker.mqtt.0
mqtt.0				2022-04-17 14:15:11.728	info	starting. Version 2.7.4 in /opt/iobroker/node_modules/iobroker.mqtt, node: v12.22.10, js-controller: 4.0.21
```
The ENOTFOUND repeats every second until the instance is stopped.
ioBroker is running on a RasPi 3b+ with Debian 11 (bullseye) as 192.168.1.150 (WLAN) and 151 (LAN).
localhost is 127.0.0.1 in /etc/hosts plus an additional entry iobrokerpi with 127.0.1.1

It worked until yesterday. Then I updated a few adapters (roughly 7 methinks) and after that I tried to install Sonoff as a new adapter.  That one didn't show up, neither as instance nor as adapter. It was late so I decided to continue the next day.

Today the only success was "iob add sonoff" via Putty (right now I'm missing the + and - signs in the adapter overview page) showing adapter and instance. But MQTT still can't find localhost and Google isn't a help any further.

Ah, btw: In the settings dialog of MQTT the "test connection" button just says "error" in a window where a full trace dump would fit. ;-)

**Comment by miriki** [comment]
( Sorry, i mixed things up. My prepared message was intended for another page, although this one discusses the same error message. So I deleted my comment again. )
