### ISSUE TITLE
Typescript example

### ISSUE THREAD

**Issue by sandeep-eroad** [mqttjs/MQTT.js#1281]
Can someone show me an example of how to use this in typescript?

**Comment by sandeep-eroad** [comment]
Anyone?

**Comment by sandeep-eroad** [comment]
Does any version of this lib works with React Native app?

**Comment by dgg** [comment]
I don't know whether this library works with React Native as I do not personally use it.
As for the typescript example, my team and I are using typescript. What kind of example are you looking for?
Would a simple connect, subscribe, publish, handle message suffice?

**Comment by YoDaMa** [comment]
Hey @dgg, they didn't respond, but if you create a PR for a typescript example folder that would be very appreciated.

The goal with vNext is to move this library to Typescript natively, which will reduce some of the typing bugs we keep running into. If you have suggestions on features / support / designs you'd like to see in our next major version release, please contribute to the discussion here: https://github.com/mqttjs/MQTT.js/discussions/1324

Closing this issue now because initial person has not responded in a while.
