### ISSUE TITLE
LWT is published by broker on client.end() using ws

### ISSUE THREAD

**Issue by youngcholo** [mqttjs/MQTT.js#1316]
The broker is publishing the LWT on the client.end() using ws.

Tested it with TCP and works fine, only with ws.

Maybe the disconnect packet was not sent on end/close?

test code : 

```
"use strict";

let mqtt = require("async-mqtt");

let options = {
  port: "15675",
  host: "ws://172.16.10.76",
  path: "/ws",
  clientId: "mqttjs_Eddy1_0117642a-c577-4323-bc98-4217a9f8f56f0.5591469928486372",
  keepalive: 60,
  reconnectPeriod: 1000,
  protocolId: "MQIsdp",
  protocolVersion: 3,
  clean: true,
  encoding: "utf8",
  username: "nltapp",
  password: "nltinc",
  will: {
    topic: "dm-chat/user/status/response/600",
    payload: "{\"userId\":6,\"status\":\"Away-LWT\",\"timeSent\":null}",
    qos: 1,
    retain: true
  }
};

console.log("connecting mqtt client");
let client = mqtt.connect("ws://172.16.10.76:15675/ws", options);
console.log(client);
client.on("error", function (err) {
  console.log(err);
  client.end();
});

client.on("connect", function () {
  console.log("client connected:" + options.clientId);
  client.subscribe("/a", { qos: 0 });
  client.publish("a/", "wss secure connection demo...!", { qos: 0, retain: false });
  client.end();
});

client.on("message", function (topic, message, packet) {
  console.log("Received Message:= " + message.toString() + "\nOn topic:= " + topic);
});

client.on("close", function () {
  console.log(options.clientId + " disconnected");
});

```

**Comment by youngcholo** [comment]
Verified with Wireshark  : 

TCP client : disconnect packet is sent on .end()
WS : disconnect packet is not sent on .end()

https://drive.google.com/file/d/1KHk3n75NuTfHhDtfNKCFQHJf7DMpXI2g/view?usp=sharing

**Comment by youngcholo** [comment]
@mcollina Please have a look

**Comment by YoDaMa** [comment]
Thanks for identifying @youngcholo. Could you spike a PR to fix this?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by YoDaMa** [comment]
So this bug is:

- TCP Connection sends `.end()` over the wire
- WS Connection does **not** send `.end()` over the wire.

Now my understanding is that the logic for `ws` and `tcp` when it comes to ending is exactly the same. This is the code that closes the stream being used: https://github.com/mqttjs/MQTT.js/blob/dbdbe454a21df49d1ee7ead8dda3444c50b66065/lib/client.js#L1050

Since they're the same logic, I wonder if the logs on the client would be the same, but maybe the stream is closed at a bad time with ws so the `disconnect` packet doesn't make it to the broker. This would explain the [LWT](https://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament/) (Last Will and Testatment) from the ungraceful disconnect.
