### ISSUE TITLE
Can't connect to Mosquitto server using WebSockets

### ISSUE THREAD

**Issue by federicochiesa** [mqttjs/MQTT.js#1347]
If I try with another client and the same exact parameters I can connect to a Mosquitto server, but with MQTT.js I can't connect. It doesn't show any errors, it just hangs and client.on("connect") is never called. 

I'm using MQTT.js in a CLI Node.js app.

Here are the MQTT parameters: ![Screen Shot 2021-10-24 at 21 17 54](https://user-images.githubusercontent.com/38504010/138609361-3b43f6f2-5b5f-4a41-8b14-4687afdf0129.png)
 
Here is the code I'm using to connect: 
```js
var client = mqtt.connect({
    host: 'ws://192.168.1.28',
    port: 1884,
    username: '**********',
    password: '**********'
});
```

**Comment by martinneumann** [comment]
Same issue here. We found that Mosquitto 2.14 is not compatible with mqtt.js. We reverted back to 2.11 and websockets connect again.

I am not 100% sure, but it appears that MQTTExplorer uses mqtt.js under the hood, which is why the same problem happens.

Running mosquitto in the console, the connection gets rejected with a "2", meaning "client id rejected". This only happens with websockets.

So, solution for now, unfortunately: downgrade Mosquitto.
