### ISSUE TITLE
On new message the existing data gets removed

### ISSUE THREAD

**Issue by ashiqdey** [mqttjs/MQTT.js#1468]
In react when we listen for messages and after getting the messages when we push the payload to array  only the last instance is saved and the previous payload received gets replaced. Am I doing something wrong or there is issue in the mqtt package because I am not able to figure out whats the issue with my limited knowledge?

```
const [messages,setMessages] = useState([1,2,3]);

client.on("message", (topic, message) => {
    const payload = JSON.parse(new TextDecoder("utf-8").decode(message));

    setMessages([...messages,payload]);
});
```

Outputs:
```
1st output : [1,2,3, "payload 1"]
2nd output : [1,2,3, "payload 2"]
expected output : [1,2,3, "payload 1", "payload 2"]
```

**Comment by doc-han** [comment]
Since the `client.on("message", cb)` is giving you a message both times, then it's not a problem with the MQTT library.

If both payloads are sent in approx. the same time then use `setMessages(messagesState=>[...messagesState, payload])` since `setMessages` does asynchronous work and messages might have not been updated yet when the next payload came in.

**Comment by ashiqdey** [comment]
> Since the `client.on("message", cb)` is giving you a message both times, then it's not a problem with the MQTT library.
> 
> If both payloads are sent in approx. the same time then use `setMessages(messagesState=>[...messagesState, payload])` since `setMessages` does asynchronous work and messages might have not been updated yet when the next payload came in.

yes this  `setMessages(messagesState=>[...messagesState, payload])` solved the issue

**Comment by doc-han** [comment]
great
