### ISSUE TITLE
Module not found: Error: Can't resolve 'url' in 'E:\project\mqtt-client\node_modules\mqtt\lib\connect'

### ISSUE THREAD

**Issue by hyyky** [mqttjs/MQTT.js#1558]
what's the problem

**Comment by hyyky** [comment]
When I run with the version 2.6 of vue, an error is introduced
![image](https://user-images.githubusercontent.com/50724513/202995615-112900e9-69c3-4496-9851-afeb60e226d8.png)
![image](https://user-images.githubusercontent.com/50724513/202995669-130a500c-b2c7-4299-bdc5-9a5a1233ea8d.png)

**Comment by hyyky** [comment]
Node.js v14.17.5

**Comment by Vamoss** [comment]
Same here

Node.js v16.15.1

**Comment by gklasen** [comment]
Did you guys resolve?

**Comment by Vamoss** [comment]
I ended up using this:
https://www.npmjs.com/package/precompiled-mqtt

**Comment by zhutianyu888** [comment]
import mqtt from "mqtt/dist/mqtt";

**Comment by robertsLando** [comment]
I have fixed [Browser](https://github.com/mqttjs/MQTT.js#browser) docs by adding webpack and vite setup. Check them out

**Comment by TheDam1999** [comment]
Did you guys resolve?

**Comment by David-OConnor** [comment]
Looks like not.

**Comment by David-OConnor** [comment]
Still broken on my end.

**Comment by cc0cc0cc0** [comment]
This is because you used webpack version 5.0 and above. According to the instructions on npm mqtt, just modify the webpack configuration. [mqtt readme](https://www.npmjs.com/package/mqtt?activeTab=readme)
If you get errors when building your app with webpack v5, it's because starting from v5, webpack doesn't polyfill Node.js core modules anymore. You can fix this by adding the following to your webpack config:

const NodePolyfillPlugin = require("node-polyfill-webpack-plugin")

module.exports = {
    Other rules...
    plugins: [
        new NodePolyfillPlugin()
    ]
}

**Comment by David-OConnor** [comment]
I don't have a webpack config.

**Comment by David-OConnor** [comment]
Same error.

**Comment by David-OConnor** [comment]
Thank you for the suggestion. Unfortunately, it does not change the error state on my end.

**Comment by cc0cc0cc0** [comment]
you have write the wrong place in   webpack config，there have some “plugins” in it，write it near  “new HtmlWebpackPlugin”。
