### ISSUE TITLE
How can I call publish a message from receiving a message only once. As of now it is resending the message repeatedly when a message is triggered. 

### ISSUE THREAD

**Issue by xtianus79** [mqttjs/MQTT.js#1567]
I have come up with the method below of using count and only allowing 1 send per count == 1 but there has to be something I am doing wrong. 

My use case is, I want to send a message from a client. Upon receiving the message I want to trigger a function that will make a call. After the rest call is returned I then want to publish back to another client. I need to track the topic as well. If I don't use the count statement then it will keep sending the publish trigger over and over. 

```mqttJs.client.on('message', async (messageTopic, payload) => {
  console.log('Received Message:', messageTopic, payload.toString());
  let count = 0;
  if (payload && count == 1) {
    count++
    await red(messageTopic);
    console.log('count', count);
  }
```

**Comment by eye-c** [comment]
consider using a state library

**Comment by robertsLando** [comment]
you have to use a different topic, otherwise you will create a loop. A common use case is to send requests to a topic with a suffix and responses to the same topic without the suffix.

Example `clientXX/myApi/set` (request) ---> `clientXX/myApi` (response).

So the client that sends the requests needs to publish to `clientXX/myApi/set` and subscribe to  `clientXX/myApi`
