### ISSUE TITLE
Does mqtt.js support tcp?

### ISSUE THREAD

**Issue by jikoy** [mqttjs/MQTT.js#1581]
Does mqtt.js support tcp?

**Comment by jikoy** [comment]
this.client = mqtt.connect("tcp://broker-cn.emqx.io:1883/mqtt", this.options);

**Comment by jikoy** [comment]
this.client = mqtt.connect("tcp://broker-cn.emqx.io:1883/mqtt", this.options);

![图片](https://user-images.githubusercontent.com/10125432/220007501-7297f784-7320-4f84-a0e9-26e17aca1761.png)

**Comment by jsiegenthaler** [comment]
I use mqtt over a tcp websocket no problem

				mqttClient = mqtt.connect('wss://mqttservername.com/mqtt', {
					connectTimeout: 10 * 1000, // 10s
					clientId: mqttClientId,
					username: mqttUsername,
					password: mqttPassword
				});

**Comment by Noobmaster69-bug** [comment]
MQTT is a protocol built on top of the TCP/IP stack so MQTT.js support TCP, of course.

**Comment by TheNovemberRain** [comment]
Due to browser limitations, you cannot establish a TCP connection directly in your browser. However, all modern browsers support the establishment of TCP-based WebSocket connections. Therefore, your MQTT server needs to support WebSocket connections, otherwise you might need a service that converts TCP to WebSocket.

**Comment by robertsLando** [comment]
Browser only works with websockets
