### ISSUE TITLE
Client keeps trying to reconnect indefinitely 

### ISSUE THREAD

**Issue by WarburnEstate** [mqttjs/MQTT.js#1600]
Hi,

Is there a way to set a limited amount of time the client can try to reconnect? when there is an issue with the connection the client just keep spamming connection request indefinitely which could cause issues

**Comment by navneetlal** [comment]
Adding the solution here since i was also facing this issue and came across this ticket 
[https://www.npmjs.com/package/mqtt#enabling-reconnection-with-reconnectperiod-option](https://www.npmjs.com/package/mqtt#enabling-reconnection-with-reconnectperiod-option)
You can set reconnectPeriod: 0 to disable auto reconnect.

```ts
const mqttClient = mqtt.connect('mqtt://connectionstring:1883', {
    connectTimeout: 1000,
    reconnectPeriod: 0
})
```
