### ISSUE TITLE
Restore subscribtions after reconnect in deferred open scenario

### ISSUE THREAD

**Issue by raajeshk88** [mqttjs/MQTT.js#166]
Hi,
   I am using MQTT(client ) and Mosquitto(broker). I have clients which will be subscribed to the broker always. If the the broker restarts or goes down the client is not able to re-connect or throw any error. Is this also related to #112 and #148. I am using mqtt 0.3.8. My client is created as
client = mqtt.createClient(PORT,MQTT_SERVER, { encoding : 'binary', username : MQTT_USERNAME, password : MQTT_PASSWORD, clientId : 'backend'});

**Comment by mcollina** [comment]
Thanks to @mdickens we have support for the `sessionPresent` bit in CONNACK.

Here is my proposal to address this issue:

1. _everything_ happens before connect goes into a 'special' storage  that will be replayed every time there is a reconnect if the `sessionPresent` bit is not set.
2. the `'connect'` event is fired only _when a new session is created_, while the `'reconnect'` event will be fired thereafter.

What do you think? Anybody that would like to give it a go?

**Comment by mcollina** [comment]
@gorhgorh @256dpi any of you two wants to tackle this?

**Comment by jdiamond** [comment]
I'm not so sure about logging everything before connect to replay on reconnect for these reasons:

- it's possible to publish before connect--why replay those?
- it's possible to subscribe after connect-- why not replay those?

If MQTT.js tracked what topics (and their QoS levels) get subscribed to, it could automatically resubscribe regardless of whether the subscription happened before or after connecting.

Since it's possible to unsubscribe at any time, MQTT.js should probably update its list of active subscriptions after an unsubscribe to avoid resubscribing to those topics.

If sessionPresent is set in the connack packet, MQTT.js should only replay the QoS 0 subscriptions. Otherwise, it should resubscribe to all topics?

Does this sound right?

**Comment by mcollina** [comment]
I'm not sure about publish commands, but the behavior you describe for subscribe sounds perfect.

**Comment by jdiamond** [comment]
Haven't had much time to finish this, but I have made progress here:

https://github.com/jdiamond/MQTT.js/tree/resubscribe-on-reconnect

It's not done, but I'll submit a PR as soon as I'm able.

**Comment by mcollina** [comment]
Thanks :). No hurry
Il giorno mer 20 gen 2016 alle 04:39 Jason Diamond <notifications@github.com>
ha scritto:

**Comment by mcollina** [comment]
@psorowka maybe we should implement this :P. It is causing a lot of issues.. https://github.com/mcollina/mosca/issues/435

**Comment by psorowka** [comment]
phew... let's have a chat about that somewhere.. this sounds like a lot automagic. if we really touch this, I'd have a lot more suggestions, some of which would be... 

- add explicit option for auto-reconnect / auto-restore-subscriptions so users know what they do
- add subscriptions not via a `subscribe` function but rather provide some configuration like `ensureSubscriptions` and probably attach subscription-wise message handler callbacks at the same place.
- provide more callbacks / promises instead of event emitters (more natural program flow)
- .....

**Comment by psorowka** [comment]
while reading through that again: all of this should probably not go into mqttjs. but we could create something like a convenience-wrapper-library with all the automagic (`comfort-mqtt.js`) and let the original `mqtt.js` stick more closely to the specs

**Comment by mcollina** [comment]
Currently MQTT.js has a lot of automagic going on, it automatically reconnects, and it implements the deferred open scenario for publish and subscribe. The problem is that the whole reconnection setup is implemented wrong for subscribes: a reconnection without `clean: false` will loose the subscribes. Given the fact that deferred open is hard and reconnection are hard, I think we should implement both here. This leaves with very few option on what to do for subscribes.

I'm ok with having some more option to control auto-reconnect, restore-subscribtions etc.
I'm also ok in splitting this into two modules: one without the autoreconnect stuff, and one with auto-reconnect, promises etc (maybe even adding a dependency on QLobber here to provide the routing for individual callbacks). I would keep the mqtt module as full-featured as possible, and maybe move all the rest into `mqtt-core`. However, this will take time, and we should probably release v2 with this auto-subscribe sooner.

Anybody that wants to contribute this feature? Any other opinions?

**Comment by psorowka** [comment]
we are working on similar stuff internally (also e.g. SRV lookups for connecting) and most probably make in OpenSource anyway.. I can well imagine contributing this to mqtt.js. But it will take some more time...

**Comment by mcollina** [comment]
If you would like to contribute the automatic-resubscription here, we can go ahead and release v2 :)

**Comment by spacekitteh** [comment]
@psorowka 

> we are working on similar stuff internally (also e.g. SRV lookups for connecting) and most probably make in OpenSource anyway.. I can well imagine contributing this to mqtt.js. But it will take some more time...

Were SRV lookups ever implemented?
