### ISSUE TITLE
Connect hangs using ws:// in Node.js, works in browser

### ISSUE THREAD

**Issue by tuukka** [mqttjs/MQTT.js#278]
Running under Node.js (v0.10.37), mqtt.connect('ws://...') hangs (fails to connect). It works if ran in a browser, however. If I change the protocol to 'mqtt://', it connects under Node.js as well as in the browser. I'd expect the ws protocol to work under Node.js too.

I'm testing mqtt.js version 1.1.3 from NPM against an IBM MessageSight server.

**Comment by mcollina** [comment]
Yes it works. I am not sure about MessageSight as I do not have one, and this project is not sponsored by IBM. It would be great if you could suggest a fix for your issue and submit a pull request.

If it works in the browser with 'mqtt' it's because it's falling back to 'ws', which is kind of wrong.
Are you switching between the right ports for ws and mqtt (they do not run on the same port)?

**Comment by mcollina** [comment]
Closing, feel free to reopen.

**Comment by tuukka** [comment]
Thanks, this was actually a problem in the NodeJS websocket library and fixed by this pull request: https://github.com/websockets/ws/pull/494
