### ISSUE TITLE
Export UMD

### ISSUE THREAD

**Issue by jmeas** [mqttjs/MQTT.js#337]
Offloading the bundling of this library to the consumer makes it more difficult to consume the library, I think. Many libraries to do the heavy lifting for consumers by exporting a UMD version of the module. This makes the installation instructions drastically simpler. By exporting UMD they might look something like:

> Install it with npm:
> 
> `npm install mqtt`
>
> Use it wherever you want; the exported file supports Node / AMD / CJS / ES2015 / browser globals

Webpack is one tool that can do this pretty simply. This makes it slightly more work to maintain the library, as ya need to remember to run the build before each release. But it's not so much extra work, I think :)

**Comment by RangerMauve** [comment]
Exporting UMD directly won't make sense since this library has a bunch of dependencies that are on NPM. It might be useful to have a bundled version in the releases, though.

**Comment by jmeas** [comment]
@RangerMauve , how is having dependencies a problem for npm? For AMD/CJS/ES2015 environments, they'll automatically be bundled by end users. For browser globals environments, the consumer will need to load up each dependency manually.

> It might be useful to have a bundled version in the releases, though.

That's definitely an option! I usually just leave the deps out of the build and it works great.

**Comment by RangerMauve** [comment]
If you take a look at the [package.json](https://github.com/mqttjs/MQTT.js/blob/master/package.json#L47), you'll notice that there are 11 dependencies. And I think it's safe to assume that most of them do not offer a UMD wrapper. As well, UMD is great when you have a self-contained module, but it's very crappy for dealing with external dependencies since there's a bunch of different ways to do it and they're all mostly incompatible. As well, this project only really works in the browser when browserified since it has [configs](https://github.com/mqttjs/MQTT.js/blob/master/package.json#L41) specifically for that. Granted, as far as I recall, Webpack also supports the `browser` field.

I totally see the point of having a bundle that's easily accessible to people since it wasn't entirely user friendly to build the bundle when I initially started playing with this client-side.

Also, I guess [this was kinda brought up before](https://github.com/mqttjs/MQTT.js/issues/300).

**Comment by sandro-k** [comment]
Just to let you know. I am bundling MQTT.js for the <mqtt-elements> to load MQTT.js for the <mqtt-connection> element. Yesterday I wrote some test for the project and discovered that I need to change the bundling of the library to have access to `new Store()` to be able to create the store before creating the `MqttClient`. With that in mind I think providing a bundled version often helps to get stared, but you often have to specifically build it for your use case.

**Comment by mcollina** [comment]
I'm :-1: on exporting an UMD, but I'm :+1: on providing an already built library. We need to automate that, so doing a release is easy. The options are either to add the bundle in a `dist/` folder, or to stick it into the GH release (and automate that). Anybody that wants to send a PR?

**Comment by sandro-k** [comment]
This example looks promising http://dontkry.com/posts/code/browserify-and-the-universal-module-definition.html

**Comment by jmeas** [comment]
> If you take a look at the package.json, you'll notice that there are 11 dependencies. And I think it's safe to assume that most of them do not offer a UMD wrapper.

Ah, fair point.

> I totally see the point of having a bundle that's easily accessible to people since it wasn't entirely user friendly to build the bundle when I initially started playing with this client-side.

I agree with you; I think a bundle makes sense.

> Also, I guess this was kinda brought up before.

Woops. Searched for UMD and didn't see anything. I'll have to search better next time :)

> I'm :-1: on exporting an UMD

How come?

**Comment by RangerMauve** [comment]
@mcollina Were you thinking that the dist would just be on NPM, or on Github as well? Because if it was the former, the easiest route would be a prepublish script in the package.

**Comment by mcollina** [comment]
@RangerMauve I think we should publish it on Github, rather than NPM. If the target host uses NPM, we can safely assume it is using browserify/webpack/*, so no need for UMD.

@jmeas this library is built to exploit dependencies coming from NPM, so we can update them safely in case of bugs. An UMD bundle will break all of that, by bundling everything on a single file. Moreover, an UMD is really hard to debug (ok we can add sourcemaps). Finally this library should run well on both Node and the Browser. Currently it is easier to run on Node than the Browser, and we should not break one to fix the other.

**Comment by mcollina** [comment]
Closing, if somebody is still interests we'll reopen.
