### ISSUE TITLE
documentation: examples for connecting to AWS IOT

### ISSUE THREAD

**Issue by vielmetti** [mqttjs/MQTT.js#340]
The AWS IOT service requires use of certificates, and their sample documentation uses `mosquitto` to illustrate how to make the connection, per

http://docs.aws.amazon.com/iot/latest/developerguide/iot-quickstart.html

A useful documentation addition would be transliterate these `mosquitto` invocations to instead use `MQTT.js`, and to verify that a similarly constructed sample would work. I'll submit a PR if I manage to get it to work.

**Comment by sandro-k** [comment]
PR is alway welcome. Have a look at https://github.com/aws/aws-iot-device-sdk-js how they connect `awsIot.device` to there MQTT broker.

**Comment by pfried** [comment]
I am currently trying to set up a connection to aws iot via mqtt over websockets.

There is an official  [example](https://github.com/awslabs/aws-iot-examples/tree/master/mqttSample), which uses the paho javascript client and some additional code to compute the signature (aws v4) you need to append to the url.

Right now i did not manage to connect altough the url looks good and the signature should be fine. A closer look on the headers of the websocket request showed that the paho client sets a different header. Paho sends

`Sec-WebSocket-Protocol:mqtt`

but this library sends:

`Sec-WebSocket-Protocol:mqttv3.1`

My config is like this:
```
    this.client = MQTT.connect(this.endpoint, {
      protocolId: 'MQTT',
      protocolVersion: 4,
      clean: true,
      clientId: 'MyClient',
    });
```

I am getting a `403` response which indicates problems with the authentication. Unfortunately i dont know how long a signature is valid since it contains a timestamp, but i will try to copy and paste the one from the example.

I found this issue related: https://github.com/beerfactory/hbmqtt/issues/38, which basically says by spec it should work even if the wrong header is set. I guess the paho client does it right (`mqtt`) and this lib kind of wrong (`mqttv3.1`).

Has anyone managed to get this lib working with aws iot? Could the header be an issue?

Cheers!

**Comment by mcollina** [comment]
cc @gkwicker might help

**Comment by gkwicker** [comment]
Hi @pfried, the easiest way to connect your JS application to AWS IoT is using the [AWS IoT SDK for JavaScript](https://github.com/aws/aws-iot-device-sdk-js).  It handles all of the authentication for you, and includes documentation as well as Node.js and browser application examples.  We monitor that repo as well as the [AWS Forums](https://forums.aws.amazon.com), so if you have any questions or issues about AWS IoT, please let us know there.  Thanks for your interest in AWS IoT.

**Comment by pfried** [comment]
Alright i will try that, no idea why i did not try that first, but the example provided uses the paho client, so maybe thats where that idea came from. Thank you

**Comment by mcollina** [comment]
Closing this :).
