### ISSUE TITLE
Can not specify encoding in v2. Why?

### ISSUE THREAD

**Issue by kmamykin** [mqttjs/MQTT.js#465]
Seems like in v2 there was a breaking change to remove `encoding` from options and all strings are encoded as text.

The problem I am facing right now is when connected to AWS IoT mqtt gateway over WebSocket, the gateway drops connection with "Text or Continuation frame is not supported" error.

It happens initially when sending "connect" packet and `protocolId` and `clientId` are encoded as text frames. I tried passing Buffers for the values, and got a bit further, but then subscribing to topics errored as well, and there the logic inside mqtt-packet assumes and validates the topics are strings.

The same code works well on 1.4.x version.

I would like to know what precipitated the change?

**Comment by mcollina** [comment]
This was not wanted, and in case it is a bug. 
The problem you are describing is Websocket specific.

I think a similar issue was fixed in the latest release of websocket-stream. Can you please check if you are using the latest version?

Can you please upload a script and instructions on how to reproduce this problem?

If you are using this from AWS-IoT-sdk, it might be better to include them in triaging and fixing.
