### ISSUE TITLE
move to uws as its a fastest ws implementation?

### ISSUE THREAD

**Issue by cordovapolymer** [mqttjs/MQTT.js#490]
As per [uWS README ](https://github.com/uWebSockets/uWebSockets/blob/master/README.md) its much faster tha WS which is used underneath MQTT.js WebSocket implementation.
`ws v1.1.0 + binary addons `	`µWS is 47x as lightweight` 	`µWS is 18x as performant` 	`µWS is 33x as performant `	`µWS is 2x as performant`

Would you consider moving to it?

**Comment by mcollina** [comment]
This library uses `websocket-stream`, which has its own issues on how we are using it (see other reported issues on v2.0.x).

I think:

a. we should make `websocket-stream` pluggable, so that we can use it with `uws`.
b. make `websocket-stream` behave like a true binary stream, which currently does not.

I'm co-maintaining that library, so send PR there if you want to help :).
