### ISSUE TITLE
auto reconnect bug

### ISSUE THREAD

**Issue by Shinjifei** [mqttjs/MQTT.js#618]
The auto reconnect functionality is effectively DoS'ing my mqtt broker.  The reconnect process is broken

Source File is Client.js
`MqttClient.prototype.subscribe` is called and at the end of this function, 

 `this._sendPacket(packet)` is called.

The first few line in sendPacket 

```
MqttClient.prototype._sendPacket = function (packet, cb) {
  if (!this.connected) {
    if (packet.qos > 0 || packet.cmd !== 'publish' || this.queueQoSZero) {
      this.queue.push({ packet: packet, cb: cb })
    } else if (cb) {
      cb(new Error('No connection to broker'))
    } return
  } 
```

This adds the topics to be resubscribed on connect to a queue.  This happens for every 1second that the client is disconnected.  If a client is disconnected for day that will be roughly 86400 topics in the queue.  When the client finally connects it subscribes to the same topics however many times it was added to the queue. 

```
// Send queued packets
  this.on('connect', function () {
    var queue = this.queue

    function deliver () {
      var entry = queue.shift()
      var packet = null

      if (!entry) {
        return
      }

      packet = entry.packet

      that._sendPacket(
        packet,
        function (err) {
          if (entry.cb) {
            entry.cb(err)
          }
          deliver()
        }
      )
    }

    deliver()
  })
```

I have clients that literally could disconnect for days or weeks at a time and this queue grows without limit.

**Comment by RangerMauve** [comment]
That sounds pretty awful. This seems like it was introduced with the automatic resubscribe feature that was added a while ago. Would it make sense to de-dupe the subscription packets? Or would the issue be somewhere else?

**Comment by Shinjifei** [comment]
I am positive this was introduced with the automatic resubscribe feature.  If the auto resubscribe is to be left in, yes the queue needs to remove dups or never have dups added.  

We honestly didnt need the functionality at all in the way we wire up our client.  We set our subscriptions onConnect.  When a client gets disconnected by default it tries to reconnect every 1000ms. When it connects a event is triggered and we subscribe there.  To alleviate this issue we are clearing out this variable onConnect after we client.AddSubscription: `this.client._resubscribeTopics = {};` 

So on initial connect and on every connected after a successfull reconnect _resubscribeTopics are cleared.  So the topics are never added to the queue when the client tries to reconnect every 1000ms

**Comment by RangerMauve** [comment]
Would a quick way forward be to make the auto-resubscribe be optional and configurable through the config object? We could set that up initially and then look into doing a more thorough fix for this issue.

**Comment by RangerMauve** [comment]
Sadly, I'll be busy for the next week or so, but if anybody wants to do a PR, here's what we'll need:

- A new config option, maybe call it `autoResubscribe` or something similar, have it be true by default so that we're fully backwards compatible
- Modify the code [here](https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L194) to check that configuration before trying to subscribe again
- Add a unit test [here](https://github.com/mqttjs/MQTT.js/blob/master/test/abstract_client.js#L1579) to make sure the new option is being used

**Comment by mcollina** [comment]
Ahum, I think the bug should be fixed by having the re-subscription issued on `'connect'` rather than `'reconnect'`, as `'reconnect'` fires _before_ CONNACK is established:

https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L192-L197

If I understand correctly, that would remove the bug, as it will not grow the queue indefinitely for each reconnect.

**Comment by Shinjifei** [comment]
@mcollina above commit fixes the problem.

We would love to see a option to turn this feature off altogether though.

Thanks for the quick fix.
