### ISSUE TITLE
Multipe clients connecting with same clientID both keep connecting and disconnecting without error

### ISSUE THREAD

**Issue by robertsLando** [mqttjs/MQTT.js#684]
I'm using MQTT over websocket with mosca broker on server side. I connect clients by using a specific client id: `websocket_<email>-<sessionID>` and `clean` flag set to `false`. The problem occurs when user opens multiple tabs on the same page, both clients keep disconnecting and connecting in an infinite loop and I can't see any error throw or event like client event [error](https://www.npmjs.com/package/mqtt#event-error)

In mqtt readme I have found a parameter in [connack](https://www.npmjs.com/package/mqtt#event-connect) packet: `connack.sessionPresent` but it is always `false` in my case. In that case I could simply add a random string at the end of client id to make both connection work or something else to prevent the disconnection. Any idea? Is it a bug that sessionPresent is false?

**Comment by mcollina** [comment]
for `sessionPresent`  to be `true` in Mosca, you need to have an offline subscription active, as far as I remember.

In any case, if you need to support multiple windows, you must use different clientIds. I would recommend you to check out  https://github.com/mcollina/aedes. It has a simpler design than mosca.

**Comment by robertsLando** [comment]
@mcollina can you explain me better what you mean with "offline subscription"? I know I need different clientID I just wuld like to know when this happens, I mean get an error on client connect or on error event that says "Client ID already used" or something like this. Than I have check aedes but it seems the same as mosca, why should I use it insteed?

**Comment by RangerMauve** [comment]
You should append a random number to the ID so that different tabs won't collide.

Having a unique clientIID per connection is part of the [MQTT spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349242) so you don't have much choice here.

**Comment by jdiamond** [comment]
I think @RangerMauve is correct. This is just the nature of MQTT. Further on in the spec, it says:

```
If the ClientId represents a Client already connected to the Server then the Server MUST disconnect the existing Client [MQTT-3.1.4-2].
```

Unfortunately, MQTT doesn't define a way to tell the existing (older) client that it's being disconnected because a new client is using its ID--the connection just gets closed.

You should decide if you want a second tab to open a new MQTT connection or if you want to reuse the existing connection. If you want a new connection, you have no choice and must make the client ID unique. If you'd rather reuse the existing connection, you need to figure out how to share it between tabs (not sure how to do this).

In my browser-based MQTT apps, every tab gets a new connection, but I ensure they each have unique client ID. Authentication is done with usernames and short-lived access tokens in the password field so I don't really care what the client ID is.

**Comment by 5aurabh** [comment]
Is it possible to disable the reconnecting behaviour of a client? 

Suppose there are two clients with the same client ID. According to the MQTT spec, when trying to connect, the older client will be kicked out by the broker. But due to the reconnecting behaviour of the library both of these clients would end up in a loop trying to kick each other out.

Does having a flag like ``maxConnects`` in the configuration help to tackle this situation?

**Comment by andrejohansson** [comment]
Intrested in this as well, either sharing a mqtt connection between tabs (is this possible?) or keeping the client from reconnecting. I'm using this with azure iot which only allows one connection per deviceid.
