### ISSUE TITLE
Upgrade to mocha@4

### ISSUE THREAD

**Issue by mcollina** [mqttjs/MQTT.js#703]
Our test suite does not complete/exits anymore after the upgrade. It would be fantastic if someone could help.

**Comment by prabathabey** [comment]
@mcollina I'd like to take a look at this. Will provide an update as soon as I manage to come up with a sizeable contribution.

**Comment by boneskull** [comment]
I looked at this and can identify several problems:

- The reconnect timer is either really sticky or just needs an `unref()`; the interval will keep the process open. (I'm still not convinced the reconnect timer is working as intended, but that's a separate issue)
- The ping timer suffers from the same problem
- Many tests don't call `client.end()`, and if they do, they don't necessarily wait for it to finish
- The test server(s) themselves stay open

You can test this by grabbing [wtfnode](https://npm.im/wtfnode) and executing `wtfnode node_modules/.bin/_mocha` from a MQTT.js working copy.  When the process hangs, hit Ctrl-C to dump the async tasks.

I poked at this for about an hour, but IMO you're better off sticking `--exit` in `mocha.opts` unless you love pain.

**Comment by boneskull** [comment]
FWIW, calling `close()` on a `net.Server` instance doesn't disconnect any clients, which I didn't realize...

**Comment by mcollina** [comment]
Oh I didn’t know you could add a flag to mocha.opts to get the old behavior.
I would still prefer if someone could come up and clean up the current mess.

**Comment by boneskull** [comment]
not to toot my :trumpet:, but if I'm finding it difficult & tedious to clean up, I don't suppose it'll be a breeze for anyone else :wink:

**Comment by 4rzael** [comment]
I tried to do some kind of tests, where I try the connection against multiple brokers:

This is my code:
```js
const should = require('should')
const mqtt = require('../../')

describe('protocol ws', () => {
  let client
  afterEach(() => {
    if (client) {
      client.on('close', () => {
        console.log('closed')
      })
      client.end(true)
      client = undefined
    }
  })

  it('should be able to connect to the broker', (done) => {
// in my case, urls are ws://localhost:2002, ws://localhost:2012 and ws://localhost:2022/mqtt, respectively for mosca, mosquitto, and emq.
    client = mqtt.connect(URL) 
    client.on('connect', () => {
      client.connected.should.equal(true)
      done()
    })
  })
})
```

## Broker configuration

I tried running it with mosca, mosquitto and emq, using the following docker images to run the brokers:

* mosca: `matteocollina/mosca`
* mosquitto: `toke/mosquitto`
* emq: `sneck/emqttd:latest`

## results

When running `mocha test.js` against `mosca` and `emq` the process correctly quits, and when running it against mosquitto, the process hangs at the end.

I also tried using tcp instead of websockets, in which case none of them hangs.

# Wireshark

Given this difference between multiple broker, I ran wireshark on each of these tests.

### EMQ
![](https://i.imgur.com/woSvZ3I.png)

### MOSCA
![](https://i.imgur.com/4ixpd50.png)

### MOSQUITTO
![](https://i.imgur.com/Mmy4rFB.png)

## Interpretation

As we can see, emq and mosca have very similar traces, where mosquitto misses the two grey TCP packets at the end, that represent the end of the connection (closing the socket).

Therefore, it seems like this problem is at least partially due to a TCP socket not closing properly on some cases, that may be broker-dependent (mosquitto was also considerably slower, so it could also be timed-dependent).

## Resources

* [pcap files](https://drive.google.com/open?id=1BzZroDRkYK1gtqh_t_oNP4pHaIodHavM)

**Comment by boneskull** [comment]
I would also recommend pulling in https://npm.im/stoppable and wrapping the `net.Server` instances with it

**Comment by mcollina** [comment]
@4rzael this is very interesting.

Were you able to pinpoint the problem in our code (or our tests)?

**Comment by 4rzael** [comment]
Unfortunately, I didn't manage to find the problem in our code, and currently do not have the time to do further investigations.
