### ISSUE TITLE
Subscribe too many duplicate data arrive.

### ISSUE THREAD

**Issue by dlape** [mqttjs/MQTT.js#718]
Please, guys, I receive a duplicate data every time someone sends a data from me. Is there any way how to limit it to only 1?. its so annoying because I'm using it on the chat.  Is this due to my muliple subscription?.
Is there something problem implementing this?.
```js
client.on('connect', function () {
  client.subscribe('flt/stat/status', { qos: 2 });
  client.subscribe('flt/chat/id/3882', { qos:2 });
});
```

**Comment by cordovapolymer** [comment]
@dlape, maybe you call your subscribing code more than once?

**Comment by perezale** [comment]
Hi everyone, sorry if I'm not opening another report for this behaviour, but, actually there are many about resubscriptions and this one is quite similar to my situation. In a few words, I'm seeing duplicate data arrival.

I'll try to explain my case with more details:

My current connection is:
mqtt.connect(options.activemq.local.url, {
  ...auth-options...,
  "resubscribe": false
}) 
and on-connect handler is:
client.on('connect', function () {
   client.subscribe(CONSTANT)
)

The problem is that resubscription happens whether I add 'resubscribe' or 'clean' options to the connection (either true or false). 

I'm testing this situation by stopping and starting my activemq service.
The client gets reconnected after service start and fires the connect handler, where my subscriptions take place as expected.

So, if I send a message the first time (without restarting the broker service), the message handler fires only once (perfect!). But, if I send a message after restarting, the message handler is fired twice. And if I restart the broker service again, the message handler is fired three times, and so on.

I've tried using the "clean" and "resubscribe" flags and none keeps the client from resubscribing automatically.

any ideas? for now i'll try to keep track of the first connection by myself to perform subscriptions.

tested with mqttjs version: 2.15.1

**Comment by 4rzael** [comment]
@dlape Did you succesfully manage to solve your problem ?
