### ISSUE TITLE
Connecting to AWS IoT using MQTT

### ISSUE THREAD

**Issue by svj13** [mqttjs/MQTT.js#747]
Hello!

I am asking here because hopefully someone may be able to provide insight to a problem I am having! Please close/delete this issue if you feel it is irrelevant.

Long story short, I have a web browser client that sends a message to my server via websockets. Now, I want to take that message, and send it to AWS IoT from my sever using MQTT.  I do not want to send straight from my client through to AWS IoT via MQTT. I just want to use MQTT to forward a message I have received on the server.

Has anyone done this/know how to go about it? I can connect to test brokers from my back end, but not my AWS IoT.

Here is the stack overflow question here which would provide a lot more info.Thanks in advance!

https://stackoverflow.com/questions/48102490/connecting-to-aws-iot-using-mqtt-over-websockets-from-the-backend?noredirect=1#comment83180481_48102490

**Comment by jdiamond** [comment]
The options you're passing to `connect` in your SO post are full of options that aren't supported by MQTT.js. See here: https://github.com/mqttjs/MQTT.js#mqttclientstreambuilder-options

The URL you're using starts with `ws`, but I'm pretty sure AWS only supports `mqtts` and `wss`. Since you're not in a browser, there's no need to use `wss`.

IIRC, AWS requires clients to use certificates to authenticate. Your second example shows you trying to use one. I would verify I have the correct CA, cert, and key using openssl as AWS documents here: https://docs.aws.amazon.com/iot/latest/developerguide/diagnosing-connectivity-issues.html

Once I know my certificates are in order, then I would try using MQTT.js again. This time with the `ca`, `cert`, and `key` options.

To see errors, handle the `error` event. MQTT.js tries to recover from errors by automatically reconnecting, but I think you should at least see socket-level errors (which is what I assume is happening since you're trying to use a port that AWS' broker doesn't support).

**Comment by mcollina** [comment]
You should use https://github.com/aws/aws-iot-device-sdk-js to connect to aws iot. It is different enough from a plain MQTT broker to require its own module. It uses this one internally.

**Comment by ashiqdey** [comment]
How to connect to aws-mqtt using javascript on frontend without using any backend
