### ISSUE TITLE
How to change re-connect strategy to re-connect again with different credentials.

### ISSUE THREAD

**Issue by syberkitten** [mqttjs/MQTT.js#761]
Hi

Is it possible to re-connect using different credentials
every time, instead of having to clear the old instances
of MQTT client? (which might be problem in terms of cleanup or memory leaks)

**Comment by einargs** [comment]
If you're referring to altering the username/password you connect with, I'm having some success with manually changing the fields in the client's `options` field (e.g. `client.options.password = newPassword;`). However, this is undeniably a hack, and I'm hopping that there's another, better way to accomplish the same thing. For example, `Client#reconnect` [accepts an options argument](https://github.com/mqttjs/MQTT.js/blob/d58c3fe00e36e4dd876f2f020e5c5590cd8fdf5b/lib/client.js#L645) where you can pass new stores in. It would be nice if we could optionally pass an object containing options that we want to update.

Part of the reason that this method concerns me is that the [initial options object is stored in the `streamBuilder` wrapper that the client calls to build a new connection](https://github.com/mqttjs/MQTT.js/blob/d58c3fe00e36e4dd876f2f020e5c5590cd8fdf5b/lib/connect/index.js#L135). As such, if the options object is mutated, there's no guarantee that the options the connection implementation is using will match--which, as far as I can tell, doesn't matter for things like the username and password fields. However, "as far as I can tell" makes me nervous.

Fortunately, [looking through the code](https://github.com/mqttjs/MQTT.js/blob/d58c3fe00e36e4dd876f2f020e5c5590cd8fdf5b/lib/connect/index.js#L122), the `streamBuilder` (the wrapper the client calls to get a new connection) has the client passed to it when it's called--which means that the wrapper could just look at the client's options object instead of using the initial one.

Of course, I'm unfamiliar with the codebase, so there could easily be stuff I'm missing.

P.S. apologies if I screwed the terminology up--"connection"/"connection implementation" is probably the wrong word, but I couldn't think of anything better. I'm basically referring to the result of `streamBuilder`, which should hopefully be clear from context/the linked code.

---

On a side note, I should probably explain why I need to be able to update the password field. Google Cloud IoT Core [requires](https://cloud.google.com/iot/docs/how-tos/credentials/jwts#required_claims) that you send a signed JSON web token in the `password` field to authenticate the device. This token has a maximum lifetime of twenty-four hours (plus skew). This limits the usefulness of a stolen token, which seems (to my inexperienced self) rather reasonable.

However, this need to update the password field means that I either need to basically rebuild the client every time the token expires--which is, uh, *non-optimal*--or hack around with the options object, which seems to work, but makes me nervous that I'm going to run into an error later on down the road where I need to use a different protocol or modify a different field and everything's going to break in some really subtle and hard to diagnose way.

**Comment by mcollina** [comment]
Would you like to make a proposal (PR) on how to improve the current situation?

**Comment by einargs** [comment]
Sure. I'm not sure how quickly I'll be able to get it done--I'm trying to catch up on a backlog of school work--and I've never actually made a pull request before, but I'll try to have something by Friday? Probably sooner, if I'm honest.

**Comment by einargs** [comment]
@mcollina where/how should I ask questions about what I should implement? For example, where should I ask if I should try to extract functionality related to loading-in options into a separate private method?

**Comment by mcollina** [comment]
You open a PR and we discuss them.

**Comment by einargs** [comment]
Does that mean that I should open the PR before I have any changes made?

(Apologies for the silly/basic questions.)

**Comment by mcollina** [comment]
@einargs I mean those changes are very hard to reason about without code that implements them. Propose some changes on how things should work, and we'll work from there.

**Comment by drmikecrowe** [comment]
@einargs I just got bit by this token expiration.  How did you detect it?  I didn't receive an error event, so I'm curious how that notified your application

**Comment by WilliamHolmes** [comment]
@einargs Another option could be sending a `options` as a function rather than a object. It might be more flexible if others options need changing. ie. expired username/password.

**Comment by RangerMauve** [comment]
You could define a getter on the options object which returns different credentials every time. 😂

**Comment by ivands** [comment]
I also want to use this lib with AWS IOT.
The problem am facing is as followed.
My streamBuilder function returns a promise that will later resolve.
This is required to lazily refresh AWS IAM credentials and sign the url.

```javascript
const client = mqtt.MqttClient(function(){
  const credentials = await IAM.credentials();
  const signedUrl = ...
  return websocket(signedUrl, [ 'mqttv3.1' ]);
});
```

Can we get promise support for the streamBuilder parameter?

**Comment by RangerMauve** [comment]
Hi ivands. I'd suggest synchronously returning a stream, then piping your websocket into it once your promise resolves. 

Something like this:

- Create two PassThrough streams, one for input, and one for output
- Create a duplex stream using the two passthrough streams. I'm sure there's something on NPM for this
- Create a promise to get credentials. Once it resolves, create the websocket stream, pipe the input into it, and pipe it into the output.
- Return the duplex stream synchronously

That way you can have your actual stream get created asynchronously, without needing to change anything in the library.

Otherwise, if you want to add asynchronous support, it'll require changing [_setupStream](https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L277) in the Client implementation to handle promises (or preferably node-style callbacks). I think a PR which adds unit tests and is backwards compatible would be welcome in that case.

**Comment by ivands** [comment]
Thanks @RangerMauve that solution works perfectly well.

**Comment by collindutter** [comment]
@ivands would you mind sharing some relevant code snippets? I haven't worked with streams much so I'm still a bit lost.

**Comment by YoDaMa** [comment]
this issue seems to be resolved with the documentation provided for `transformWsUrl`, so I will close this issue. Feel free to reopen.
