### ISSUE TITLE
React Native MQTT via TCP

### ISSUE THREAD

**Issue by andonivianez** [mqttjs/MQTT.js#798]
Hi!
I´ve put everything working on React Native´s 0.54.2 version, but I´m having an issue that maybe you had on your iteration...:
I put the connect method like this:
```js
let url = '192.168.1.108'; 
let mqtt = require('mqtt'); 
let client = mqtt.connect({ servers: [{ host: url, port: 1883 }], keepalive: 60, protocol: 'mqtt', });
```

But on React Native´s console, when I debug the MqttClient, I got this:
captura de pantalla 2018-03-27 a las 12 39 06
It looks like is not getting the options I´m passing to the client...how can I fix it? Did you get working without websockets using this library?
Thanks in advance!

**Comment by RangerMauve** [comment]
I don't think we can get this module to work with the TCP version of MQTT due to React-Native not supporting the `net` module that we need for node.js. 

You might be able to mess around with aliasing to alias `net` as [react-native-tcp](https://github.com/PeelTechnologies/react-native-tcp).

You'll want to modify the [package.json](https://github.com/mqttjs/MQTT.js/blob/master/package.json#L59) in mqtt.js.

Add a new field called `react-native` which is the same as the `browser` field, but with `"./mqtt.js"` pointing to `"./mqtt.js"` and aliases for the other three modules (net, tls, fs) point to react-native equivalents.

You might also want to consider using [nodejs-mobile-react-native](https://github.com/janeasystems/nodejs-mobile-react-native) which will allow you to just use the raw node.js version of this library without having to shim it to work with RN. The only caveat is you'll need to coordinate between RN and Node.js with events, which shouldn't be too hard.

**Comment by thomaslc66** [comment]
Hey @andonivianez did you manage to find or do something ? 
I was also using mqtt with react-native but all i founded was some npm lib using websocket but non of them using mqtt / tcp

**Comment by andonivianez** [comment]
I finally used mqttjs over websockets, because it´s the most stable connection actually good supported for RN.
As an alternative, it´d be possible to write a native module passing events to nodejs... but actually, I recommend ws-mqtt ;)  (with mqttjs)
