### ISSUE TITLE
WebSocket connection errors not catched

### ISSUE THREAD

**Issue by DurandA** [mqttjs/MQTT.js#876]
When connecting to an invalid url using WebSocket, the error is not dispatched to 'error' event function (`client.on('error')`).

For example, `mqtt.connect('ws://invalid.hostname/')` output in console:
```
WebSocket connection to 'ws://invalid.hostname/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
```

However, this event is impossible to catch, including with `try...catch` statements.

**Comment by linrong** [comment]
I also encountered this problem. Can you find a solution? @pkuczynski

**Comment by pkuczynski** [comment]
It was a while ago and I don't remember :(

**Comment by mgetka** [comment]
The issue has been created some time ago, but since it is one of the top results from google for related problems i will leave my insights here.

HTTP error codes cannot be handled while using the websockets interface due to security considerations of the protocol. Refer to the [section 5 of W3C WebSocket API specification](https://www.w3.org/TR/websockets/#feedback-from-the-protocol) for more details.

> User agents must not convey any failure information to scripts in a way that would allow a script to distinguish the following situations:
> 
>  * A server whose host name could not be resolved.
>  * A server to which packets could not successfully be routed.
>  * A server that refused the connection on the specified port.
>  * A server that failed to correctly perform a TLS handshake (e.g., the server certificate can't be verified).
>  * A server that did not complete the opening handshake (e.g. because it was not a WebSocket server).
>  * A WebSocket server that sent a correct opening handshake, but that specified options that caused the client to drop the connection (e.g. the server specified a subprotocol that the client did not offer).
>  * A WebSocket server that abruptly closed the connection after successfully completing the opening handshake.
>
> In all of these cases, the the WebSocket connection close code would be 1006, as required by the WebSocket Protocol specification. [WSP]
> 
> Allowing a script to distinguish these cases would allow a script to probe the user's local network in preparation for an attack.

This limitation is always true for web browser based environments, it might not necessarily be of much relevance in other websockets implementation environments.

**Comment by pkuczynski** [comment]
Still not working...
