### ISSUE TITLE
Is it possible to wait until notifying the broker about consuming a message?

### ISSUE THREAD

**Issue by Gadi-Manor** [mqttjs/MQTT.js#885]
My problem is this:
I have a publisher and a consumer. I successfully established a persist session (using clean: false, qos: 2) and in fact I see that messages sent to the consumer while offline are consumed at its startup. 
But I need something more. I want that in case the consumer crashes in the middle of handling a message, then when It goes back up it will consume it again,

I notice that if the consumer crashes immediately then it consume the same message when I run it again but in case of the smallest timeout before crashing it doesn't happened. I guess it's because the notification to broker comes really close to emitting the 'message' event. 

In another words, I'm looking for something like accept/reject.

**Comment by isabo** [comment]
@Gadi-Manor: The MQTT protocol appears not to have explicit support for abandoning messages. However, using QoS 1 or 2, I suppose we could just not send an acknowledgement if we abandon the message. This should cause the broker to send a duplicate later.

In order to do this, it seems we have to override the `MqttClient.handleMessage` method to call the callback with an error if we decide to abandon, or just not call it at all in that case. `handleMessage` looks like it was written with this purpose in mind.
