### ISSUE TITLE
Reload certificate of a TLS connection

### ISSUE THREAD

**Issue by vincent-boulin** [mqttjs/MQTT.js#916]
Hello,

I need to use MQTT.js over TLS and it work fine using this configuration (i use self sign-certificate) :
```
let client = mqtt.connect('wss://my-server:my-port', {
    clientId: 'test',
    protocol: 'wss',
    ca: [ fs.readFileSync('./client_cert/ca.pem') ],
    cert: fs.readFileSync('./client_cert/client.pem'),
    key: fs.readFileSync('./client_cert/client-key.pem'),
    rejectUnauthorized: false,
    checkServerIdentity: () => { return null; }
})
```

With this i can connect and publish / subscribe on topics without problems.

Howhever in our certificate chain we want to renew the client certificate frequently.
I try the [reconnect](https://github.com/mqttjs/MQTT.js#mqttclientreconnect) method, but it doesn't take into account the new replaced certificates.
Is there a way to achieve this ?

Thank you in advance.

**Comment by AuspeXeu** [comment]
The call of `fs.readFileSync` returns the contents of that file. This means it will be stored in the options object of the client. Simply print `console.log(client.options)` by updating the options accordingly before a `reconnect` you should be able to fix this issue.

**Comment by sk4ry** [comment]
Ok, i see that and i try to change directly inside the ```client.options``` object (```client.options.cert``` and ```client.options.wsOptions.cert```), and it take into account the new certificate.

However when i call ```client.reconnect()``` this will loop like that (i log all the event) :
reconnect event | connected event | close event | reconnect event | connected event | close event etc...

I don't understand why this happen or if it's an expected behaviour, but i need to do :
```javascript
client.end()
client.reconnect()
```
to avoid the reconnect loop.
Is there an other way to achieve this ?

**Comment by lurtze1** [comment]
I am also running into this issue, is was @vincent-boulin correct in his assumption that the only way to reload the cert is via a reconnect?
