### ISSUE TITLE
Best way to handle publishing at high frequency

### ISSUE THREAD

**Issue by redstubble** [mqttjs/MQTT.js#925]
Hi, I am publishing multiple topics over a high frequency. 
Although MQTT is processing publish commands, (not blocking) however it is filling up my event loop causing laggyness. Is there a documented process to use a queue or to overcome these issues.

**Comment by Vishalz003xd9h** [comment]
Any update on this bug ?

**Comment by redstubble** [comment]
I couldn't find a solution to this. I ended up batching where possible but far from an ideal solition

**Comment by Vishalz003xd9h** [comment]
@redstubble, the batching solution will drastically reduce the high throughput required in embedded applications.

**Comment by Vishalz003xd9h** [comment]
@adamvr , @mcollina , @4rzael , @scarry1992 -  Any updates on this issue ?

**Comment by 4rzael** [comment]
Hi !
Can you please post a very simple example that exhibits this behaviour ?
I'll try to take a look at it

**Comment by Vishalz003xd9h** [comment]
Ok, So, my setup is as follows:
I am using Node JS with MQTT library for publishing json messages to a C program which will consume those published messages and return back some json responses to which the Node JS MQTT client has been subscribed to. 
The Node JS program publishes at a very high frequency of 100 to 150 milliseconds. So, during the publishing, the Node JS receives mismatched json messages but the C program is publishing it correctly. 

Output Sample:
Node JS Logs:
Message 1:
MQTT Send {"shield":"06","functionCode":"03","startRegister":"07dc","numberOfRegisters":"0002"}
MQTT Receive { shield: '06',
  functionCode: '03',
  numberOfDataBytes: '02',
  data: '61dd',
  timestamp: '1561159394310.771240' }

Message 2:
MQTT Send {"shield":"06","functionCode":"03","startRegister":"07e4","numberOfRegisters":"0001"}
MQTT Receive { shield: '06',
  functionCode: '03',
  numberOfDataBytes: '04',
  data: '0062329c',
  timestamp: '1561159394432.804688' }

C Program Logs:
1)
2019:05:21:23:2 Received Message: {"shield":"06","functionCode":"03","startRegister":"07d0","numberOfRegisters":"0001"}
MQTT Publish Message {"shield":"06","functionCode":"03","numberOfDataBytes":"02","data":"61dd","timestamp":"1561159394310.771240"}

2)
2019:05:21:23:2 Received Message:   {"shield":"06","functionCode":"03","startRegister":"07dc","numberOfRegisters":"0002"}
MQTT Publish Message {"shield":"06","functionCode":"03","numberOfDataBytes":"04","data":"0062329c","timestamp":"1561159394432.804688"}

3)
2019:05:21:23:2 Received Message:   {"shield":"06","functionCode":"03","startRegister":"07e4","numberOfRegisters":"0001"}
MQTT Publish Message {"shield":"06","functionCode":"03","numberOfDataBytes":"02","data":"ffa6","timestamp":"1561159394553.134277"}

So, as you can see here, the "timestamps" and the "startRegister" keys of the JSON mismatch. 

This continues for the entire length of publication of messages.

The Node JS event loop is getting lagged because of high frequency.

**Comment by Vishalz003xd9h** [comment]
@4rzael, Any views on it ?

**Comment by Vishal8523** [comment]
Hi, @4rzael , Any views ?

**Comment by 4rzael** [comment]
Hi, I'm sorry, I have been way more busy than I expected at work, so I haven't found the time to take a look at it yet... (Do you have a code example, so I can replicate it as easily as possible, please ?)

**Comment by Vishal8523** [comment]
@redstubble , Can you share the batching solution that you implemented ?

**Comment by Vishal8523** [comment]
@mcollina , Any updates on this issue ?
Do you suggest any method to avoid it ?

**Comment by Vishal8523** [comment]
@4rzael , Any updates on this issue ?

**Comment by 4rzael** [comment]
Hi,
I haven't been able to find any problems when publishing at high frequency: On a project I'm currently working on, we sometimes publish every 10ms (100Hz), and we are not facing any sort of lag.
We're using MQTT.js with the Mosquitto broker.

BTW, if you're trying to use MQTT for a request-response protocol, I don't think using the timing at which messages arrive as your way to know which response comes from which request is a good idea, though, as there is no guaranty in the order of arrival.

**Comment by thameera-lh** [comment]
> Hi @Vishal8523
> I haven't been able to find any problems when publishing at high frequency: On a project I'm currently working on, we sometimes publish every 10ms (100Hz), and we are not facing any sort of lag.
> We're using MQTT.js with the Mosquitto broker.
> 
> BTW, if you're trying to use MQTT for a request-response protocol, I don't think using the timing at which messages arrive as your way to know which response comes from which request is a good idea, though, as, IIRC, there is no guaranty in the order of arrival.

Hi @Vishal8523 
I too faced a similar issue, what do you mean by "MQTT for request-response protocol"?
Do we have to set specific parameters in mosquitto broker for high-frequency publishing?

**Comment by RavidAshurov** [comment]
Hi @4rzael 
We are using the aws-iot-device-sdk that uses mqtt.js.
When publishing to an mqtt topic in about 15hz, it seems that the RAM consumption is going through the roof what makes our node.js app crash after a while.

Are you familiar with that issue? is there a workaround?
Thanks

**Comment by robertsLando** [comment]
@ducanh2110 without some code it's hard to say what's going on here

**Comment by ducanh2110** [comment]
This is client initialization
` const mqttConnect = (host, mqttOption) => {
    setConnectStatus('Connecting');
    setClient(mqtt.connect(host, mqttOption));
  };

  useEffect(() => {
    const host = '******';
    const options = {
      keepalive: 60,
      clientId: connectionId,
      username: '*****',
      password: '*****',
      protocolId: 'MQTT',
      protocolVersion: 5,
      clean: true,
      reconnectPeriod: 1000,
      connectTimeout: 30 * 1000,
    };
    mqttConnect(host, options);

    return () => {
      setConnectStatus('Disconnecting');
      setClient(null);
    };
  }, [connectionId]);`
  This is for using for subscribe:
  `      client.subscribe(topicToSubcribe, { qos }, (error) => {
        if (error) {
          console.log('error on sucscribe', error);
        }
      });`
      `client.on('message', (topic, message) => {
        const payload = {
          topic,
          message: decodePriceStreamingMessageString(message.toString()),
        };
        // console.log(payload.message);
        fireMessageByType(payload);
      });`
      fireMesssageByType will send to Emitter. But there's somewhere in project has setTImeout to handle some UI elements.
      Does we using subscribe not subscribeAsync make the problem?

**Comment by robertsLando** [comment]
The settimeout happens in your code so the problem is not on mqttjs

**Comment by ducanh2110** [comment]
Okay thanks. So evenIf I subcribeAsync the setTimeOut of mqtt.js still make our setTimeout not work?

**Comment by robertsLando** [comment]
YEah
